apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-azure-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/KUBE-POD404/opslora-helm-charts.git
    targetRevision: main
    path: opslora-helm/infra/rabbitmq
    helm:
      releaseName: rabbitmq-azure-prod
      valueFiles:
        - values.yaml
        - values-prod.yaml
        - values-azure-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: opslora-app-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

