apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullname }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- toYaml .Values.labels | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}

  selector:
    matchLabels:
      {{- toYaml .Values.selectorLabels | nindent 6 }}

  template:
    metadata:
      labels:
        {{- toYaml .Values.selectorLabels | nindent 8 }}

    spec:
      automountServiceAccountToken: {{ .Values.pod.automountServiceAccountToken }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}

      {{- if and .Values.affinity.enabled .Values.affinity.podAntiAffinity }}
      affinity:
        podAntiAffinity:
          {{ .Values.affinity.podAntiAffinity.type }}:
            - weight: {{ .Values.affinity.podAntiAffinity.weight }}
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- toYaml .Values.selectorLabels | nindent 20 }}
                topologyKey: {{ .Values.affinity.podAntiAffinity.topologyKey }}
      {{- end }}
      {{- if .Values.azureKeyVault.enabled }}
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Values.azureKeyVault.secretProviderClassName | default (printf "%s-akv" .Values.secretName) }}
      {{- end }}


      containers:
        - name: lora-ai-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}

          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}
          {{- if .Values.azureKeyVault.enabled }}
          volumeMounts:
            - name: secrets-store-inline
              mountPath: /mnt/secrets-store
              readOnly: true
          {{- end }}


          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          {{- end }}

          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            successThreshold: {{ .Values.probes.readiness.successThreshold }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          {{- end }}
