apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    {{- toYaml .Values.service.labels | nindent 4 }}

spec:
  type: ClusterIP
  selector:
    {{- toYaml .Values.service.selectorLabels | nindent 4 }}

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP