fullname: docs-site-test
image:
  repository: acropsloratestcin001.azurecr.io/opslora-app-docs
  tag: "azure-test-9-f88d774"
  pullPolicy: Always
ingress:
  enabled: true
  name: docs-ingress
  className: azure-application-gateway
  annotations: {}
  hosts:
    - host: docs-test.opslora.com
      paths:
        - path: /
          pathType: Prefix
  backend:
    name: docs-service
    port: 80
