fullname: docs-site-test
image:
  repository: acropsloratestcin001.azurecr.io/opslora-app-docs
  tag: azure-test-10-50bb13b
  pullPolicy: Always
ingress:
  enabled: true
  name: docs-ingress
  className: azure-application-gateway
  annotations:
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: opslora-wildcard-le
    appgw.ingress.kubernetes.io/ssl-redirect: 'true'
  hosts:
  - host: docs-test.opslora.com
    paths:
    - path: /
      pathType: Prefix
  backend:
    name: docs-service
    port: 80
