{{- if .Values.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: order-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "order.labels" . | nindent 4 }}
spec:
  encryptedData:
    DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
    JWT_SECRET_KEY: {{ .Values.secrets.JWT_SECRET_KEY | quote }}
    ENVIRONMENT: {{ .Values.secrets.ENVIRONMENT | quote }}
    ACCESS_TOKEN_EXPIRE_MINUTES: {{ .Values.secrets.ACCESS_TOKEN_EXPIRE_MINUTES | quote }}
    API_URL: {{ .Values.secrets.API_URL | quote }}
    RABBITMQ_URL: {{ .Values.secrets.RABBITMQ_URL | quote }}

  template:
    metadata:
      name: {{ .Values.secretName }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
