fullname: landing-site-test
image:
  repository: acropsloratestcin001.azurecr.io/opslora-landing-site
  tag: azure-test-10-4e57a77
  pullPolicy: Always
ingress:
  enabled: true
  name: landing-ingress
  className: azure-application-gateway
  annotations:
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: opslora-wildcard-le
    appgw.ingress.kubernetes.io/ssl-redirect: 'true'
  hosts:
    - host: test.opslora.com
      paths:
        - path: /
          pathType: Prefix
  backend:
    name: landing-service
    port: 80
