fullname: landing-site-prod
image:
  repository: acropsloraprodcin001.azurecr.io/opslora-landing-site
  tag: "v2.0.0"
  pullPolicy: Always
ingress:
  enabled: true
  name: landing-ingress
  className: azure-application-gateway
  annotations: {}
  hosts:
    - host: opslora.com
      paths:
        - path: /
          pathType: Prefix
  backend:
    name: landing-service
    port: 80
