gateway:
  enabled: false
ingress:
  enabled: true
  name: frontend-ingress
  className: azure-application-gateway
  annotations:
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: opslora-wildcard-le
    appgw.ingress.kubernetes.io/ssl-redirect: 'true'
  hosts:
  - host: app.opslora.com
    paths:
    - path: /
      pathType: Prefix
  backend:
    name: frontend-service
    port: 8000
image:
  tag: v2.1.0
  repository: acropsloraprodcin001.azurecr.io/opslora-frontend-service
