gateway:
  enabled: false

image:
  tag: "5d1873d"

ingress:
  enabled: true
  name: frontend-ingress
  className: azure-application-gateway
  annotations: {}
  hosts:
    - host: app-test.opslora.com
      paths:
        - path: /
          pathType: Prefix
  backend:
    name: frontend-service
    port: 8000

