fullname: frontend-service-test
replicaCount: 1
image:
  tag: 5d1873d
route:
  hostnames:
  - test.opslora.com
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 150m
    memory: 512Mi
pod:
  automountServiceAccountToken: true
affinity:
  enabled: false
autoscaling:
  enabled: false
