gateway:
  enabled: false
image:
  tag: "azure-test-7-27e8fa3"
  repository: acropsloratestcin001.azurecr.io/opslora-frontend-service
ingress:
  enabled: true
  name: frontend-ingress
  className: azure-application-gateway
  annotations: {}
  hosts:
    - host: app-test.opslora.com
      paths:
        - path: /
          pathType: Prefix
  backend:
    name: frontend-service
    port: 8000
