sealedSecret:
  enabled: false

storageClass: default

azureKeyVault:
  enabled: true
  keyVaultName: "kv-opslora-test-cin-001"
  tenantId: "7f02300f-0f1b-4237-b981-c376377f394e"
  identityClientId: "e83032ad-75e0-4b4a-9495-c206dcbdebeb"
  secretProviderClassName: "spc-opslora-test-rabbitmq"
  secrets:
    - objectName: "opslora-test-rabbitmq-default-user"
      envName: "RABBITMQ_DEFAULT_USER"
    - objectName: "opslora-test-rabbitmq-default-pass"
      envName: "RABBITMQ_DEFAULT_PASS"
