{{- if .Values.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"

spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: {{ .Values.secrets.RABBITMQ_DEFAULT_PASS | quote }}
    RABBITMQ_DEFAULT_USER: {{ .Values.secrets.RABBITMQ_DEFAULT_USER | quote }}
  template:
    metadata:
      name: {{ .Values.secretName }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
