apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: rabbitmq
  annotations:
    argocd.argoproj.io/sync-wave: "-2"

spec:
  serviceName: {{ .Values.name }}
  replicas: 1

  selector:
    matchLabels:
      app: rabbitmq

  template:
    metadata:
      labels:
        app: rabbitmq

    spec:
      securityContext:
        fsGroup: 999
      {{- if .Values.azureKeyVault.enabled }}
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Values.azureKeyVault.secretProviderClassName | default (printf "%s-akv" .Values.secretName) }}
      {{- end }}

      initContainers:
        - name: fix-erlang-cookie-permissions
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              if [ -f /var/lib/rabbitmq/.erlang.cookie ]; then
                chown 999:999 /var/lib/rabbitmq/.erlang.cookie
                chmod 600 /var/lib/rabbitmq/.erlang.cookie
              fi
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq


      containers:
        - name: rabbitmq
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent

          ports:
            - name: amqp
              containerPort: 5672
            - name: management
              containerPort: 15672

          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"

          securityContext:
            runAsUser: 999
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          volumeMounts:
            {{- if .Values.azureKeyVault.enabled }}
            - name: secrets-store-inline
              mountPath: /mnt/secrets-store
              readOnly: true
            {{- end }}
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq

          livenessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 10
            periodSeconds: 5

  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
      spec:
        storageClassName: {{ .Values.storageClass }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.storageSize }}
