apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullname }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
  selector:
    matchLabels:
      {{- toYaml .Values.selectorLabels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.selectorLabels | nindent 8 }}
    spec:
      automountServiceAccountToken: {{ .Values.pod.automountServiceAccountToken }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: docs-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
