apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "notification.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      {{- include "notification.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "notification.selectorLabels" . | nindent 8 }}

    spec:
      automountServiceAccountToken: false
      serviceAccountName: {{ .Values.fullName }}-sa

      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - rabbitmq
                topologyKey: "kubernetes.io/hostname"

        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "notification.selectorLabels" . | nindent 20 }}
                topologyKey: kubernetes.io/hostname
      {{- if .Values.azureKeyVault.enabled }}
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Values.azureKeyVault.secretProviderClassName | default (printf "%s-akv" .Values.secretName) }}
      {{- end }}


      containers:
        - name: notification-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}

          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}
          {{- if .Values.azureKeyVault.enabled }}
          volumeMounts:
            - name: secrets-store-inline
              mountPath: /mnt/secrets-store
              readOnly: true
          {{- end }}


          resources:
            {{- toYaml .Values.resources | nindent 12 }}
