{{- if .Values.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: notification-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "notification.labels" . | nindent 4 }}

spec:
  encryptedData:
    RABBITMQ_URL: {{ .Values.secrets.RABBITMQ_URL | quote }}
    FROM_EMAIL: {{ .Values.secrets.FROM_EMAIL | quote }}
    FROM_NAME: {{ .Values.secrets.FROM_NAME | quote }}
    SMTP_HOST: {{ .Values.secrets.SMTP_HOST | quote }}
    SMTP_PASS: {{ .Values.secrets.SMTP_PASS | quote }}
    SMTP_PORT: {{ .Values.secrets.SMTP_PORT | quote }}
    SMTP_USER: {{ .Values.secrets.SMTP_USER | quote }}
  template:
    metadata:
      name: {{ .Values.secretName }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
