sealedSecret:
  enabled: false
gateway:
  enabled: false
ingress:
  enabled: true
  name: customer-ingress
  className: azure-application-gateway
  annotations: {}
  hosts:
    - host: app.opslora.com
      paths:
        - path: /api/v1/customers
          pathType: Prefix
  backend:
    name: customer-service
    port: 3000
image:
  tag: v2.0.0
  repository: acropsloraprodcin001.azurecr.io/opslora-customer-service
