apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-namespace-azure-test
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: https://github.com/KUBE-POD404/opslora-helm-charts.git
    targetRevision: azure/agic-application-gateway
    path: opslora-helm/infra/app-namespace
    helm:
      releaseName: app-namespace-azure-test
      valueFiles:
        - values.yaml
        - values-test.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: opslora-app-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

