apiVersion: v2
name: inventory
description: Inventory microservice for Opslora
type: application
version: 0.1.0
appVersion: "1.2.2"

annotations:
  artifacthub.io/description: "Inventory service"
  artifacthub.io/license: Apache-2.0
