azureKeyVault:
  enabled: true
  keyVaultName: "kv-opslora-test-cin-001"
  tenantId: "7f02300f-0f1b-4237-b981-c376377f394e"
  identityClientId: "771a6c04-9dd8-4fa5-98ee-5444933373bd"
  secretProviderClassName: "spc-opslora-test-inventory"
  secrets:
    - objectName: "opslora-test-inventory-database-url"
      envName: "DATABASE_URL"
    - objectName: "opslora-test-inventory-jwt-secret-key"
      envName: "JWT_SECRET_KEY"
    - objectName: "opslora-test-inventory-environment"
      envName: "ENVIRONMENT"
    - objectName: "opslora-test-inventory-access-token-expire-minutes"
      envName: "ACCESS_TOKEN_EXPIRE_MINUTES"
    - objectName: "opslora-test-inventory-api-url"
      envName: "API_URL"
    - objectName: "opslora-test-inventory-rabbitmq-url"
      envName: "RABBITMQ_URL"

sealedSecret:
  enabled: false

gateway:
  enabled: false

ingress:
  enabled: true
  name: inventory-ingress
  className: azure-application-gateway
  annotations: {}
  hosts:
    - host: app-test.opslora.com
      paths:
        - path: /api/v1/inventory
          pathType: Prefix
  backend:
    name: inventory-service
    port: 3000

