gateway:
  enabled: false

ingress:
  enabled: true
  name: order-ingress
  className: azure/application-gateway
  annotations:
    appgw.ingress.kubernetes.io/backend-path-prefix: /
  hosts:
    - host: app-test.opslora.com
      paths:
        - path: /api/v1/orders
          pathType: Prefix
  backend:
    name: order-service
    port: 3000

