apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification-service-azure-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KUBE-POD404/opslora-helm-charts.git
    targetRevision: test/opslora-helm-test
    path: opslora-helm/apps/notification
    helm:
      releaseName: notification-service-azure-test
      valueFiles:
        - values.yaml
        - values-test.yaml
        - values-azure-test.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: opslora-app-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
