apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}-migrate
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: OnFailure

      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command: ["python", "-m", "app.init_db"]

          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}