apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullName }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    {{- include "customer.labels" . | nindent 4 }}

spec:
  type: ClusterIP
  selector:
    {{- include "customer.selectorLabels" . | nindent 4 }}

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP