fullName: invoice-service
replicaCount: 3
image:
  repository: ghcr.io/kube-pod404/opslora-invoice-service
  tag: 920bd25
  pullPolicy: IfNotPresent
global:
  host: opslora.com
route:
  hostnames:
  - opslora.com
  path:
    type: PathPrefix
    value: /api/v1/invoices
  backend:
    name: ''
    port: 3000
secretName: invoice-secret
config:
  ORDER_SERVICE_URL: http://order-service:3000
  AUTH_SERVICE_URL: http://auth-service:3000
serviceAccount:
  create: true
  name: ''
pod:
  automountServiceAccountToken: false
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1
affinity:
  enabled: true
  podAntiAffinity:
    enabled: true
    type: preferredDuringSchedulingIgnoredDuringExecution
    weight: 100
    topologyKey: kubernetes.io/hostname
resources:
  requests:
    cpu: 50m
    memory: 150Mi
    ephemeral-storage: 300Mi
  limits:
    cpu: 100m
    memory: 300Mi
    ephemeral-storage: 500Mi
probes:
  startup:
    enabled: false
    path: /api/v1/invoices/health
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 12
  readiness:
    enabled: true
    path: /api/v1/invoices/health
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3
  liveness:
    enabled: true
    path: /api/v1/invoices/health
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
secrets:
  ACCESS_TOKEN_EXPIRE_MINUTES: AgDm4SdKnIKQlBtKL/bM/6AZADh8i7ByZZjKb0Kz5fo5SwxXe6kBiOL6NDDkqU7VJCFGpaInfU+1XMqu20eUohYvO8PZ8xBOxIpHjKwsyNuxAzHLb1J4mZg3dJqcj+xn79Rr9nbEIl1K7LFzJo2KK12bYlagXUTrJvEoLtZ5Hk26avnMrzItXhIUCNfS2CquLvbfOpY/6fFJaonDCUGY2zJZ/XJEm+qWcgn9yAJkaCp80J+cOZRN8BDZ2OeQuRE32+LnixXYKcc2iCBifIwdjUWPTlCefUoEuxxOrHv3+JdzCtILJR/QWwAYob/6NG3WYgoNBtpVc0I24TgrwZaK2dKeOKTQzuHEGy3v30EUq1Bna9LH9con56xaYR1JlBcLKME+lvfw7rfzI23BNg8743JOiRIe/YcnhK5Wx82OQiRBDg03XVVk2/B/b+xGdLaOFnNnjVFeqF/lgN6vl+rQSMQzP5bqbjqGybCGv6b81P5xc2jTutdkWHA3/7z0Y5b052X5QuVCoyrYnm6q520qTc6LoWn4agbjQU44S500BS5Y9YdZyWA0pdAT0c7NJ/QEAddsqVu1j/c70nmId6SDh+rGJ9iLhKcHp/zaX1AtFLbszkph79l3uU3qoX7dESuvEKdy/bTZ47G9AbUtdSfkxw2V+qZm9Vd4WFM58I2V/mOMgvpQfuc3vLfKYp+dA5knIhS00q4=
  API_URL: AgBaN9TrnJENwt6K0bhP4eUIuh4nxDK7B13AEjwoH3FGJwXuJc07RZsrd7XW7JQe7vxar5H73XEHL/aTr4hrgQuDjy5AuDWTnBr5yV2sJ9kqJUg0eq28XGKBbE0tSu9QGfLu1N0eHHQU639bSPUbKCSKjcr4qkfn8BHJgv70bjl0ro5pXFhr8Bx4rJMjhA1+qLowDGEPqRLSit/VwBq0xQWJY8tY0NDSAPcjngU+Id4z7C9XQlG3Ov3aycfxjIzm4W1PJqoG3pCl5Iwf3QvS0h1jhxAfZ2QmWQzSrg/cN2j2cyOCNN8s85jwNYbjftdRjOl7L/E19nf2pHn1134Z53ZNE/MUpW6bWmjLUd4K5EwigsovO1PwH1RuEETvpDOFDdEUeU93agegQFUPAiyGHc4r7GiYCmPvPFz4wFcFNUs1pWKTnowMs516++9J18qlnAPPnpcFMFZG+RSDlTYZkYo0XPqSpHfDXNQ0d4+LWUXX77h11ZiclyCDG1YI7OjVJiYx+18gl84zSgunso7VlUi25FulWHbG2cs/HfXVnN6POMkt8TckoA2Jgm3mutRTVmbQQpVyeZZZzibTF3xULezTimOmbwfyvokrDC5R+oo3dqQTGqNIVJd68BYpshZ3N9J5Krct6NDYJ95ZuyUciu8xU6WcuLPylQ7+3oZhq3V6zjFhjUM7KIMFqk7XTD6IU1bqpJMyZmO1
  DATABASE_URL: AgDvwACIEujrKWVuaGGgBIuc0zclqUdBlLotllJ2W5Fa4bu37URUbqGSVLTC+aIDYe97s/OQzj/LrvWOFY6Qv6/mFh0G7kTnknewL0wYBMMtr/NS948ytTCTyPfTBFfLsQjaOP8uitmC+goTBNTlkUClrpOs7PlMHBOe2j0CqNSc1ODIEmvlLt8IyqNZV+47ejTcBL9z/yizSaJytvplBzpvZtgGdKyObEVxdd0fUu7sdlaelr5drJfVG4MB+4PQLg1HghcCNF+9uPmE4+mrklzgsEnbh7iOhhrVsUZcmxCnlf8tjmcNYQAx7w/d9Kdj+UaR7UrqHwnbu+wcAA/POOKxFk5XDIPBh0NfpMYPDPNmGtH+LnFcYVi92NTgL8Oqt3W1QZ8gaimAS7TactrjO9oMaz35rspYMNLitviB6LiB8bFiNyXDCB+Ml9Q0KyIYb9ansnv/QBNhD55ubXtfGrWn2fpeFTBRAkPwoUV1zuamgd+rytWWrpYAT34RAXt9h4CLlNjPMW9CR94rFNapDwC3Rf+1WjCetJ5YDKQMxBXM2se6d03X1X6pMYQCYHOyyNt8w4tY7H/+FzWSs3GrHYzl0JTj0p2tKi65/KA8eSDxbg062S41xUoaxEtSXcKUCYeoXp/zcBXqZVmpKRXl1JHOO/pbxUpVNUi4QmSQ6FQ1D3jiDXMDOhy8Zdf6nYhNG7p9w9TOxGIdYme3UKMXKpTPFd5imZog7o1P1eoDcWwYiopdSWNEXu2fUnJp2ilDGLtbgdhu4PWNbWrMGW4PHaH5fAhe
  ENVIRONMENT: AgCVfMS02gn3XN2Nti79gmzuh7hy+YSGPFerkD6U6iED7cq88kDSepqt/I1mJQT1TWNbjRIhZXrWaBqzG56A1lVQuMRWkhEos2y1RztZYJbbVcHH2kibCsJSAe2Xr4goe6Y0/MfBoDGfrBLFCa+3XXKULlHl/UGCbfL2SydLzzSbRlfVqxCMfnET7sA7DGvGyunyEuuUljyrUJnhbI4Nwb390+NWv5jq1LCYdy0z/ZLFXxGzzDJPaMSHaBsXE8gBgiCBGmcDT3ddmfOBMfqRNWEAfNc6W8geRbRFL80n2ijF/3kbMU8hkul7WBGmMgIcQAsXG1lbxfg+95AjZj0QBZJKRhebeeViSxnnSmyN5/l40h3QYdkDHpTkMR/EHNU1hhZLQzETjckrBky8GpBCKRa6h6xJX16/GKUzDtk8FfuMFolr1JZKS0zNSmZ4Y+csOY1iV3sa9of7ehISu6hQWhcVGxqDWcwNyCOvbLL8TvYi2ualk6XIGN0k1zKxUcbniQUtAahlfb2sgfyBXSh38KxtWjHn57cDFzfLW+HHMPs+mQWHkJJVKP9fWYKhJEvPA8HZ4oPyJnMtO5vqYiFZbtS1gr6OCVmdPk4uXiudGvjRikxUzUS893bJE5xwgTJwxkzR5yGRofg5Nr08Mb1jPeZUpnIEQtCGNYWbx0+IPBbKbt3KxMekikEi01ESKV8bcoT1u/VSTqTHUzFp
  JWT_SECRET_KEY: AgC1qjjHbbpmH7EREMBbVYZc7c80uGro4AbVzdBB6dO2H1G1JmX2JiJMF6nk3U4eszMgn+XC5Shz2hGRpWGUrxduR8ODy73xp9X+DyMOVVZI/swLlv/gHcKRNPaGPYkno7c2wwUa+pmEKdimeawIPGx/Dnprb+tDnoVI/d+bMzHZTiTDE+ke9a9pYBjm3gfSThp+W3RdCUvJp1spOCwtcCh1P1KoeKW2o5XFR2bmcFsVTtDneB7tCYO3WLLelFtCh6g0NXUdeHgmfI3qjVbz9NF0BO7rcV4XzTqmi2h1Sud05sQdytosvXZigfcQc3RDvQuThJSnDTBixFLHk/tMA0rYpP5FAnH2QVd+lOcWHIvBInvOAm2CmGYwMoHSFYriTrapphAjvzMnn1/xaiqwrMbdn5hi90lxvR2cbOOoViE8+Cv4AZb9d2MZEJ64gKeiY5fZJMTLQlxPB2CZXuyAyKmD2/PpczPKvF0DKRdQhZil5SMojyg0Za2q047GAu3UW7hccCSXt8AxOwQ6pOOuklrC6Gf/o1tImUbmxpk0q/pva0WM3O4DDJT+QLKXWaLnXDqvnaL6uuSGlZVxHPPr2rsgcV7j6wXl957bCYMnxGJZDino1bfMyMgy/2kxOngT1BYvqKfONnbTXcInC5XbZ+qMRAKrMkZPIwBKE5PIHcdC5Hasuq/SgGItuFBOKLS7JBsWJt61+0ZYTUNKtBuU6KqC2hebNCo8y+y59EeTA6NK3JpQRQAcvYg8UefavOm9e3yQC0Yu8DuB3O8K/LteplZFq1XIL8TXwdw1rK5d4HQJv46E1HDg5xYISXbx7hRcRqkBnT3vIr1haPWq6slQ2cOB2vmuBTj1EvGv/m3Q7AfI+1oNO/Hzc1akews/QpSXbHB4DaH3O+31fOfjfkgdTgIxHW/tB6DNGnuDdeylxarLGzdVuDL6vtIdsKH8eXLYr6wr6QTLz9P+y03XK153NhiGv/hoB71WEXrrQt8xYZCc/CXTUNRS91qEEcxfmAyvzMOcFTcSzowL0AO/ZAT/puqpMOTQdrFYvfZHmJZF12g96rJCt6bd2P9aIvWYDN0qLRlTjL7Y6+n2BnMbWIdLwbueTovHXp1gKTK5wCQnakzjuOzQ9Iz2/SZHChLgS2jebVIY73xw20U=
  RABBITMQ_URL: AgCuIb9BzigHSbNeISNGjJ+txlU/FK8lQqddFJ928BdaXk+RNVzpSntX2w0bUQ+lJKyIcOX5uugAi1XrUng2wB7iCErGVzwd5+WCj8RqwbpEIaWFYWE7unufuCSX5ZLcJm/Xpd12Z2U8BMr//pNk7Bnu6qQ6DZvucVdtKE4UlnRoAUdZvVNvhDsoVd66R6AGZh4iid1/wGmPWdI9mzgP2iQQTa7m7J5cSsDvxo++6w1hdl9DJqlHUzCPC/gKxDRjWM6CVhle9wex1Vjq4sfXzCQaon6DeG82AMdMAHxtUsH2N9Hw3LYjpW44BIYWsB/AE+vesXTd+hgyYzF5ZTrOwZ5cNbBQlXVzOxNUbACwHjeTtSsn8YxPn5x7oUdoUJwC9BOC6YbY5IS5mUO+KwGggU2NHKxTggS35sQuho7/Qfr1dhVF8zmeq0xYjt9syyUruYMQDdQEONCB0OeRAmsuALAE8qtqVxnnIs9SlD2S1N+t9WEo8wmiEbo7wM+2xgYcsJOj1E3NB4Ch9ycD8o6/oLId4dIe2NTMlbKWn2xEQMHb9lOTOT1bbqQ6U9QVFLMOnrXu56NlqWnUmM511pOUbry+d9VodcZzG0JnYcTZKr+fX5FlGC0rirsnCDaGS7z0sIjIDSzmB/UpPdvXU6gH2C+tDoZvyp/tk8Um4WnU4MSO4PKKtgfGQTKHyBChI0Bysvy0K88HKseEK8scBAg/RIkZFHsUvSQ75Q+W1G+h99upmndZqJQmsQpPEQ/++jquus8=
