image:
  tag: azure-test-6-a1c6d6e
  repository: acropsloratestcin001.azurecr.io/opslora-invoice-service
azureKeyVault:
  enabled: true
  keyVaultName: kv-opslora-test-cin-001
  tenantId: 7f02300f-0f1b-4237-b981-c376377f394e
  identityClientId: e83032ad-75e0-4b4a-9495-c206dcbdebeb
  secretProviderClassName: spc-opslora-test-invoice
  secrets:
    - objectName: opslora-test-invoice-database-url
      envName: DATABASE_URL
    - objectName: opslora-test-invoice-jwt-secret-key
      envName: JWT_SECRET_KEY
    - objectName: opslora-test-invoice-environment
      envName: ENVIRONMENT
    - objectName: opslora-test-invoice-access-token-expire-minutes
      envName: ACCESS_TOKEN_EXPIRE_MINUTES
    - objectName: opslora-test-invoice-api-url
      envName: API_URL
    - objectName: opslora-test-invoice-rabbitmq-url
      envName: RABBITMQ_URL
sealedSecret:
  enabled: false
config:
  ORDER_SERVICE_URL: http://order-service:3000
  AUTH_SERVICE_URL: http://auth-service:3000
gateway:
  enabled: false
ingress:
  enabled: true
  name: invoice-ingress
  className: azure-application-gateway
  annotations:
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: opslora-wildcard-le
    appgw.ingress.kubernetes.io/ssl-redirect: 'true'
  hosts:
    - host: app-test.opslora.com
      paths:
        - path: /api/v1/invoices
          pathType: Prefix
  backend:
    name: invoice-service
    port: 3000
