sealedSecret:
  enabled: false
gateway:
  enabled: false
ingress:
  enabled: true
  name: invoice-ingress
  className: azure-application-gateway
  annotations:
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: opslora-wildcard-le
    appgw.ingress.kubernetes.io/ssl-redirect: 'true'
  hosts:
    - host: app.opslora.com
      paths:
        - path: /api/v1/invoices
          pathType: Prefix
  backend:
    name: invoice-service
    port: 3000
image:
  tag: v2.1.0
  repository: acropsloraprodcin001.azurecr.io/opslora-invoice-service
azureKeyVault:
  enabled: true
  keyVaultName: kv-opslora-prod-cin-001
  tenantId: 7f02300f-0f1b-4237-b981-c376377f394e
  identityClientId: e8b9e1b0-e396-4d81-924f-465bc5a1297b
  secretProviderClassName: spc-opslora-prod-invoice
  secrets:
    - objectName: opslora-prod-invoice-database-url
      envName: DATABASE_URL
    - objectName: opslora-prod-invoice-jwt-secret-key
      envName: JWT_SECRET_KEY
    - objectName: opslora-prod-invoice-environment
      envName: ENVIRONMENT
    - objectName: opslora-prod-invoice-access-token-expire-minutes
      envName: ACCESS_TOKEN_EXPIRE_MINUTES
    - objectName: opslora-prod-invoice-api-url
      envName: API_URL
    - objectName: opslora-prod-invoice-rabbitmq-url
      envName: RABBITMQ_URL
config:
  ORDER_SERVICE_URL: http://order-service:3000
  AUTH_SERVICE_URL: http://auth-service:3000
  PAYMENT_SERVICE_URL: http://payment-service:3000
